### ISSUE TITLE
tomcat mirror 403

### ISSUE THREAD

**Issue by MatthiasHertel** [robertdebock/ansible-role-tomcat#11]
**Is your feature request related to a problem? Please describe.**
i got a 403 on tomcat_mirror see below:

![image](https://user-images.githubusercontent.com/8426566/54473574-f1b29a00-47d9-11e9-801c-61aa15bf4d57.png)

the tomcat_mirror is generated from many vars e.g. tomcat_version see below:

```
- name: install tomcat instance
  unarchive:
    src: "{{ tomcat_mirror }}/{{ tomcat_archives[instance.version | default(tomcat_version)]['url_path'] }}/{{ tomcat_archives[instance.version | default(tomcat_version)]['targz'] }}"
    dest: "{{ tomcat_directory }}/{{ instance.name }}"
    owner: "{{ instance.user | default(tomcat_user) }}"
    group: "{{ instance.group | default(tomcat_group) }}"
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: "{{ tomcat_directory }}/{{ instance.name }}/bin"
  register: install_tomcat
  until: install_tomcat is succeeded
  retries: 3

```

**Describe the solution you'd like**
 
i want to set the tomcat_mirror to official mirror not from uni delft

**Describe alternatives you've considered**
see above

**Additional context**
no
