### ISSUE TITLE
Tomcat upgrade not installed

### ISSUE THREAD

**Issue by jbrown-xentity** [robertdebock/ansible-role-tomcat#22]
## Describe the bug
When a [download of the specified version of tomcat](https://github.com/robertdebock/ansible-role-tomcat/blob/master/tasks/instance.yml#L23-L27) is called, the file is only downloaded the first time. If a new version of tomcat is specified using the `tomcat_version9` variable and the playbook is run on the same host, tomcat is not updated.

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

[latest version](https://github.com/GSA/datagov-deploy/blob/master/ansible/fgdc2iso.yml#L10)
Run on multiple hosts with tomcat already installed, every command was reported as "skipped".
```yaml
---
- name: Deploy Tomcat
  hosts: catalog-fgdc2iso
  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.java
    - role: robertdebock.tomcat
      vars:
        tomcat_version9: "9.0.37"
        tomcat_instances:
          - name: "tomcat"
            version: 9
            address: "127.0.0.1"
```

## Output

All tasks reported as "skipped".

## Environment

- Control node OS: Ubuntu 18.04.5
- Control node Ansible version: 2.8.15
- Managed node OS: Ubuntu 18.04.5

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
