### ISSUE TITLE
no test named 'boolean'

### ISSUE THREAD

**Issue by javid90khan** [robertdebock/ansible-role-tomcat#24]
## Appreciation
I really like your implementation of this. It is very clean and scalable.

## Describe the bug
I get an error "No test 'boolean'" on TASK [robertdebock.tomcat : test if tomcat_validate_certs is set correctly] 
I know this may not be happening with you but I run several ansible roles without any issues. If I comment out the 'boolean' validation it works. 

## Playbook
```yaml
---
  vars_files:
    - defaults/main.yml
  become: yes

  roles:
    - role: robertdebock.tomcat
      vars:
        tomcat_directory: /home/tomcat
        tomcat_instances:
          - name: "instance_myapp1"
            version: 8
            java_opts:
              - name: JAVA_HOME
                value: "/opt/red/java"
            shutdown_port: 8019
            non_ssl_connector_port: 8084
            ssl_connector_port: 8447
            ajp_port: 8013
            wars:
            - url: "{{ download_url }}"
```

## Output

 FAILED! => {"msg": "The conditional check 'tomcat_validate_certs is boolean' failed. The error was: template error while templating string: no test named 'boolean'. String: {% if tomcat_validate_certs is boolean %} True {% else %} False {% endif %}"}

## Environment

- Control node OS: Ubuntu 20
- Control node Ansible version: ansible 2.9.6 python version = 3.8.5
- Managed node OS: CentOS 8

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).
