### ISSUE TITLE
Tomcat instance Service fails to start on CentOS 8

### ISSUE THREAD

**Issue by javid90khan** [robertdebock/ansible-role-tomcat#29]
## Describe the bug
When I deployed an instance to CentOS 8, It could not start the tomcat instance because it could not get /bin/bash to run by default. It was alright on a local VM but not on our actual server. My suggested fix is generic and should not cause any harm.
## Playbook

```yaml
---
    - role: robertdebock.tomcat
      vars:
        tomcat_directory: /home/tomcat
        tomcat_instances:
          - name: "instance_castlemock"
            version: 8
            java_opts:
              - name: JAVA_HOME
                value: "/opt/red/java"
            shutdown_port: "{{ shutdown_port }}"
            ssl_connector_port: "{{ https_port }}"
            ajp_port: "{{ ajp_port }}"
            non_ssl_connector_port: "{{ http_port }}"
            access_log_enabled: no
            wars:
              - url: "{{ castlemock_download_url }}"
```

## Output
Main process exited, code=exited, status=203/EXEC

## Environment

- Control node OS: Ubuntu 20
- Control node Ansible version: ansible 2.9.6 python version = 3.8.5
- Managed node OS: CentOS 8
Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

## Fix
I have raised a pull request for the fix.
