### ISSUE TITLE
no test named 'boolean'

### ISSUE THREAD

**Issue by onknows** [robertdebock/ansible-role-tomcat#37]
## Describe the bug
On AWX 17.0.1  ( with Ansible  2.9.17 ) provision fails with message

```
{
  "msg": "The conditional check 'tomcat_service_enabled is boolean' failed. The error was: template error while templating string: no test named 'boolean'. String: {% if tomcat_service_enabled is boolean %} True {% else %} False {% endif %}",
  "_ansible_no_log": false
}
```

## Playbook

```yaml
- name: myplay
  hosts: myplay
  become: yes

  roles:
    - { role: java,    tags: ["java"] }
    - { role: robertdebock.tomcat,     tags: ["tomcat"] }







## Output

```
{
  "msg": "The conditional check 'tomcat_service_enabled is boolean' failed. The error was: template error while templating string: no test named 'boolean'. String: {% if tomcat_service_enabled is boolean %} True {% else %} False {% endif %}",
  "_ansible_no_log": false
}
```

## Environment

- Control node OS: AWX in container
- Control node Ansible version2.9.17
- Managed node OS: Ubuntu 18.04
