### ISSUE TITLE
Default tomcat_instances does not work out of the box

### ISSUE THREAD

**Issue by noonedeadpunk** [robertdebock/ansible-role-tomcat#42]
## Describe the bug

If you run role with just defaults tomcat will raise issue:
`java.lang.IllegalArgumentException: The AJP Connector is configured with secretRequired="true" but the secret attribute is either null or "". This combination is not valid.`

## Playbook

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)

```yaml
---
- name: Gather facts
  hosts: tomcat_all
  gather_facts: "{{ osa_gather_facts | default(True) }}"
  tags:
    - always

- name: Deploy tomcat server
  hosts: tomcat_all
  gather_facts: false
  user: root
  environment: "{{ deployment_environment_variables | default({}) }}"
  pre_tasks:
    - name: Gather additional facts
      include_tasks: "common-tasks/gather-hardware-facts.yml"
      tags:
        - always
    - include_tasks: "common-tasks/os-{{ container_tech | default('lxc') }}-container-setup.yml"
      when: not is_metal
    - include_tasks: common-tasks/unbound-clients.yml
      when:
        - hostvars['localhost']['resolvconf_enabled'] | bool
  roles:
    - role: java
    - role: tomcat

```

## Output

So eventually the issue here is that `tomcat_ajp_enabled` by default is set to true. At the same time `ajp_secret` is defined and set to empty string.

I see one of the following ways for fixing that:
- Generate `ajp_secret` by default with password_lookup
- Allow to set  `ajp_secret`  with a "default" variable rather then require to override whole `tomcat_instances` for that
- Change condition here https://github.com/robertdebock/ansible-role-tomcat/blob/master/templates/server.xml.j2#L124 to `if instance.ajp_secret | length > 0`
- Set `tomcat_ajp_enabled` to `False` by default

## Environment

- Control node OS: Ubuntu 20.04
- Control node Ansible version:  2.10.10
- Managed node OS: Ubuntu 20.04
