### ISSUE TITLE
tomcat installing to /opt/tomcat, but service trying to run /opt//opt/bin/catalina.sh

### ISSUE THREAD

**Issue by stephendwolff** [robertdebock/ansible-role-tomcat#45]
I tried deploying tomcat to Ubuntu 20.04LTS, and found that starting the service failed with the following error in syslog:

`Nov 19 07:12:04 <hostname> bash[1032]: /bin/bash: /opt//opt/bin/catalina.sh: No such file or directory`

When i looked in /opt, i found that the tomcat directory was there:

```
~# ls -al /opt/
total 12
drwxr-xr-x  3 root   root   4096 Nov 19 07:06 .
drwxr-xr-x 19 root   root   4096 Nov 19 07:10 ..
drwxr-xr-x  9 tomcat tomcat 4096 Nov 19 07:07 tomcat
~# ls -al /opt/tomcat/
total 10400
drwxr-xr-x 9 tomcat tomcat     4096 Nov 19 07:07 .
drwxr-xr-x 3 root   root       4096 Nov 19 07:06 ..
drwxr-xr-x 2 tomcat tomcat     4096 Nov 19 07:07 bin
.
.
-r--r----- 1 root   root   10488933 Nov 19 07:07 tomcat_src.tar.gz
drwxr-xr-x 7 tomcat tomcat     4096 Nov 12  2020 webapps
drwxr-xr-x 3 tomcat tomcat     4096 Nov 19 07:07 work
```

## Playbook
```yaml
---
- hosts: all
  remote_user: '{{ non_root_username }}'
  become: true
  vars_files:
    - secret
  roles:
    - robertdebock.bootstrap
    - robertdebock.core_dependencies
    - robertdebock.java
    - robertdebock.tomcat
```

Please paste the playbook you are using. (Consider `requirements.yml` and
optionally the command you've invoked.)
```yaml
- src: geerlingguy.redis
- src: robertdebock.bootstrap
- src: robertdebock.core_dependencies
- src: robertdebock.service
- src: robertdebock.java
- src: robertdebock.tomcat
```

## Output

The playbook ran without error.

## Environment

- Control node OS: macos 11
- Control node Ansible version: [e.g. 2.9.1] (`ansible --version`)
```
% ansible --version
ansible [core 2.11.6] 
  config file = <...>/playbooks/ansible.cfg
  configured module search path = ['<...>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /<...>/venv/lib/python3.8/site-packages/ansible
  ansible collection location = /<...>/.ansible/collections:/usr/share/ansible/collections
  executable location = <...>/venv/bin/ansible
  python version = 3.8.9 (default, May 10 2021, 17:25:26) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 2.11.2
  libyaml = True
```
- Managed node OS: [e.g. CentOS 7] (`cat /etc/os-release`)
```
~# cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by robertdebock** [comment]
Thanks for the issue; I'll try to reproduce and fix.

**Comment by stephendwolff** [comment]
I did have an issue with the bootstrap - as per #54. I ended up commenting out 

```
#     - name: install bootstrap packages
#       ansible.builtin.package:
#         name: "{{ item }}"
#         state: present
#       loop: "{{ bootstrap_facts_packages.split() }}"
```
in robertdebock.bootstrap/tasks/main.yml

**Comment by robertdebock** [comment]
Hm, when I deploy without specifying any variables, I get a working configuration:

```
cat /etc/systemd/system/tomcat.service
#
# Ansible managed: Do NOT edit this file manually!
#
[Unit]
Description=tomcat

[Service]
User=tomcat
Group=tomcat
ExecStart=/bin/bash /opt/tomcat/bin/catalina.sh run

[Install]
WantedBy=multi-user.target
```

I think the error is triggered by [this line](https://github.com/robertdebock/ansible-role-tomcat/blob/master/tasks/instance.yml#L85):

```
        start_command: "/bin/bash {{ tomcat_directory }}/{{ instance.name | default(tomcat_directory) }}/bin/catalina.sh run"
```

So, I guess you have the variable `instance_name` set, to something like this:
```
tomcat_instances:
  - name: "/opt/"
```


I can sort of reproduce it with the snippet above, but get extra errors too, so in my case the playbook fails.

So; please let me know if you have variables set for this role, so I can `assert` input variables better.
(Please let me know if you have set the variable `tomcat_instances` and what the values are.)

**Comment by stephendwolff** [comment]
i don't have any variables set for the role. 

```
cat /etc/systemd/system/tomcat.service
#
# Ansible managed
#
[Unit]
Description=tomcat

[Service]
User=tomcat
Group=tomcat
ExecStart=/bin/bash /opt//opt/bin/catalina.sh run

[Install]
WantedBy=multi-user.target
```

**Comment by stephendwolff** [comment]
Default tomcat_directory is `tomcat_directory: /opt`, so 

`{{ tomcat_directory }}/{{ instance.name | default(tomcat_directory) }}/bin/catalina.sh`

will come out

`/opt//opt/bin/catalina.sh`

which is what i'm seeing...

**Comment by robertdebock** [comment]
Good, in that case, I know what the issue is.

Please set `instance.name` to a name, not a directory. For example:

```yaml
tomcat_instances:
  - name: "my_tomcat"
  - name: "my_tomcat1"
```

That will create:
  - /opt/my_tomcat/bin/catalina.sh
  - /opt/my_tomcat1/bin/catalina.sh

I will add some asserts to make sure you can't use a `/` character for `tomcat_instance.name`.

Does this solve your issue? (There are more examples in [`converge.yml`](https://github.com/robertdebock/ansible-role-tomcat/blob/master/molecule/default/converge.yml).

**Comment by stephendwolff** [comment]
I didn't have instance.name set - which i think must have been the problem. Maybe you could add an assert to catch that?

**Comment by stephendwolff** [comment]
ok - so:

```
    - robertdebock.bootstrap
    - robertdebock.core_dependencies
    - robertdebock.java
    - role: robertdebock.tomcat
      vars:
        instance:
          name:
           - tomcat_aprojectname
```
worked, but started tomcat at /opt/tomcat/bin/ etc, whereas

```
    - robertdebock.bootstrap
    - robertdebock.core_dependencies
    - robertdebock.java
    - role: robertdebock.tomcat
      vars:
        tomcat_instances:
          - name: tomcat

```
didn't work - still tried to use /opt//bin.

**Comment by robertdebock** [comment]
The issue you describe is exactly what happens in CI.

Your code: (Reduced a bit)
```yaml
    - role: robertdebock.tomcat
      vars:
        tomcat_instances:
          - name: tomcat
```

Tested in CI: (Reduced a bit)

```yaml
  vars:
    tomcat_instances:
      - name: "tomcat"
```

Literally the only difference I see is the quoting, but that's not relevant.

I've also locally tried your example, which results in: (Reduced a bit)

```shell
find /opt
/opt
/opt/tomcat
/opt/tomcat/BUILDING.txt
/opt/tomcat/RUNNING.txt
/opt/tomcat/logs
/opt/tomcat/conf
/opt/tomcat/conf/tomcat-users.xsd
/opt/tomcat/lib
/opt/tomcat/lib/tomcat-jdbc.jar
/opt/tomcat/bin
/opt/tomcat/bin/tomcat-juli.jar
/opt/tomcat/bin/catalina.sh
/opt/tomcat/work
/opt/tomcat/work/Catalina
/opt/tomcat/work/Catalina/localhost
/opt/tomcat/tomcat_src.tar.gz
/opt/tomcat/README.md
/opt/tomcat/temp
/opt/tomcat/webapps/host-manager
/opt/tomcat/webapps/host-manager/index.jsp
/opt/tomcat/LICENSE
/opt/tomcat/NOTICE
/opt/tomcat/RELEASE-NOTES
```

I basically can't reproduce the issue you are facing.

Please make sure your using a recent version of this role (`ansible-galaxy install robertdebock.tomcat -f`)

You can also try to run `molecule` yourself. Go into the directory of the role and run molecule:

```shell
cd robertdebock.tomcat
molecule test --destroy=never
molecule login
```

Maybe there is something to discover there.
