### ISSUE TITLE
Can't change tomcat version per instance

### ISSUE THREAD

**Issue by marcin-github** [robertdebock/ansible-role-tomcat#49]
## Describe the bug

I can't change version of tomcat per instance.

## Playbook

```yaml
---
tomcat_instances:
  - name: "tomcat-9-test"
    version: 9
    user: "tomcat-9-test"
    group: "tomcat-9-test"

```
Changing version globaly using:

```yaml
---
tomcat_version: 9
tomcat_instances:
  - name: "tomcat-9-test"
    version: 9
    user: "tomcat-9-test"
    group: "tomcat-9-test"

```
works.

## Environment
- robertdebock.tomcat,5.3.4
