### ISSUE TITLE
Not defining group results in error.

### ISSUE THREAD

**Issue by robertdebock** [robertdebock/ansible-role-tomcat#5]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

Not defining group results in an error:

```
       tomcat_layout:
      - name: blaa
        directory: /opt/bla
        non_ssl_connector_port: 8080
        ssl_connector_port: 8443
        shutdown_port: 8005
        ajp_port: 8009
```

```
TASK [robertdebock.tomcat : ensure group exists] ******************************************************************************************************************************************************************
fatal: [server1]: FAILED! => {"msg": "'dict object' has no attribute 'group'"}
```
