### ISSUE TITLE
Move tomcat subfolder folder in a specified one after unarchive

### ISSUE THREAD

**Issue by DuffMck** [robertdebock/ansible-role-tomcat#9]
If you install multiple instances of same tomcat version, now you have to specify different directories for each of them and in the folder you still have an unfriendly name like `apache-tomcat-9.0.14`. In addition, these kind of name are uncomfortable to manage with a deploy Ansible script.

It'll be nice if you can use the instance.name or specify something like instance.folder_name in order to have a file system like: `opt\`
- tomcat-a\
  - bin\
  - ....
- tomcat-b\
  - bin\
  - ...
- ...

In alternative using different instance.directory but specify a symbolic link in a specified position.

Thanks!

**Comment by robertdebock** [comment]
I'm going to look into this, thanks for your feedback!

It may take a couple of iterations and I may ask your for some more details.

Regards, Robert de Bock.

**Comment by robertdebock** [comment]
Indeed that was a very silly design, I've changed the way this role deploys tomcats.

For example these variables:

```yaml
tomcat_instances:
  - name: "tomcat"
  - name: "tomcat-version-7"
    version: 7
    shutdown_port: 8007
    non_ssl_connector_port: 8082
    ssl_connector_port: 8445
    ajp_port: 8011
```

Now creates:
```
/opt/tomcat/${version}/bin/...
/opt/tomcat-version-7/${version}/bin/...
```

that `${version}` is something I'll try to remove so you would end up with:
```
/opt/tomcat/bin/...
/opt/tomcat-version-7/bin/...
```

Great feedback @DuffMck! Would you be able to review this role once I've changed and released this feature/bug?

Regards,

Robert de Bock.
